# Generated by Django 4.0.2 on 2022-03-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_hostel_description_alter_hostel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
