# Generated by Django 4.0.2 on 2022-03-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_student_dob_customuser_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, default='static/user/defalt.jpg', null=True, upload_to='post'),
        ),
    ]
