# Generated by Django 4.0.2 on 2022-03-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(blank=True, default='media/static/user/defalt.jpg', null=True, upload_to='post'),
        ),
    ]
